### ISSUE TITLE
CTRL-D to exit

### ISSUE THREAD

**Issue by edvb** [rain-1/s#10]
Most command line interfaces have a `CTRL-D` to exit feature which saves time instead of typeing `exit` or `quit` to close out of the interactive session. Currently this only creates a newline in s. I looked through the code and found this in `interperter_loop()`:

``` c
if (prompt(&port)) {
	if (feof(f))
		break;
	else
		continue;
}
```

If the nested `if` and `else` statment is removed, leaving only the `break;` inside `if (prompt(&port))`, `CTRL-D` apears to function as it normaly does in other CLIs.

Can this be changed to allow `CTRL-D` to work or is there some reason for this `feof(f)` test?

**Comment by rain-1** [comment]
Yes I really want Control-D to kill it like a normal shell. Thanks for looking into this! I haven't been able to figure out how.

The change you suggest makes Control-C also kill the shell which is not desired. I looked into the linenoise source https://github.com/antirez/linenoise/blob/master/linenoise.c#L828 we can do this by checking errno.

https://github.com/rain-1/s/commit/7cf242490688867e0e1e5ace2205ba70ff8e2a31
