### ISSUE TITLE
Clarify adjacent string behavior

### ISSUE THREAD

**Issue by rain-1** [rain-1/s#11]
Having two strings next to each other, whether of the same or different type results in two tokens.

```
s$ echo "a""b"
a b
s$ echo 'a'"b"
a b
```

Is this the correct behavior that we want? If so document it.

While mixing strings of different sorts together is a useful trick in bash, it is actually very hard to implement in s. For this reason I think what we currently have should either be an error or documented as expected.

**Comment by edvb** [comment]
I do not think there should be a space in between, at least that is the behavour in other shells.

**Comment by rain-1** [comment]
made this an error https://github.com/rain-1/s/commit/33eca166d1ac5643d88027be135a6bd77d061437
