### ISSUE TITLE
eval syntax is ugly because of strings

### ISSUE THREAD

**Issue by rain-1** [rain-1/s#16]
use of eval will require excessive backslashes: `eval X 'echo -n 0 | tr 0 \'\\\\0\''`

What is a better alternative? we have two different types of strings to work with.

**Comment by edvb** [comment]
I think that `eval`'s functionality can be replaced with `set` and back tick support for command substitution. This will remove the need for `eval` as it already does a lot of what set is supposed to do. This would simplify to ``set X `echo -n 0 | tr 0 '\\\\0'` `` This will also allow other previously complicated commands to be greatly simplified using this much more versatile syntax.

**Comment by rain-1** [comment]
It was decided to use a builtin instead of backticks here https://github.com/rain-1/s/issues/4 because that keeps the language simpler.

Now that we have " and ' strings, it is actually not hard to add `. Just have an enum for expansion type (replacing the `should_expand` variable), DEFAULT, NONE, EVALUATE.

I think it's a good idea to remove eval and support backticks instead. Any thoughts? Any possible concerns?

**Comment by edvb** [comment]
Yes I think backticks over `eval` would be a improvement since it can be used in more cases and does not replicate the existing `set` builtin.

**Comment by rain-1** [comment]
great https://github.com/rain-1/s/commit/cef5a2002668b681a2d1f938b72b99a667d6678d
