### ISSUE TITLE
peg the linenoise clone

### ISSUE THREAD

**Issue by rain-1** [rain-1/s#18]
pick a specific commit

**Comment by ng-0** [comment]
I'm just about to update guix' linenoise to 2105ce445821381cf1bca87b6d386d4ea88ee20d, which is one commit after a debian cve.

**Comment by rain-1** [comment]
thank you!

**Comment by rain-1** [comment]
https://github.com/rain-1/s/commit/02cb1572db35aa04c5d8d9016603bb6b1e7a43bf
