### ISSUE TITLE
set the $1 $2 $3 ... variables when executing a script

### ISSUE THREAD

**Issue by rain-1** [rain-1/s#8]
set the $1 $2 $3 ... variables when executing a script from the command line `./script arg1 arg2` and `s script arg1 arg2`.

**Comment by edvb** [comment]
I created a quick mock up, as seen below, which could be used to set the [positional parameters](https://www.gnu.org/software/bash/manual/html_node/Positional-Parameters.html) `$1`, `$2`,  ect as well as `$0`, the script name. What other [special parameters](https://www.gnu.org/software/bash/manual/html_node/Special-Parameters.html) should be added? `$#` for the number of arguments? The only problem with this is that currently `#` is an end token character so `$#` does not work right now. How can this be changed? 

``` c
char var[2] = { '0', 0 };

for (argv++; *argv && var[0] <= '9'; argv++, var[0]++)
	setenv(var, *argv, 1);
var[0]--;
setenv("#", var, 1);
```

Currently this only supports 1-9, that should be all you need right? Also `variables.c` is modified to allow single character variables which start with a number.

If this looks good then I can create a pull requests with this feature, I have some other commits I need to make as well.

**Comment by rain-1** [comment]
This sounds great!

I think we should make a bigger buffer and use sprintf though. Have a check that exits if too many args are passed. Maybe the limit should be 999 args?

```
s$ getconf ARG_MAX
2097152
```

seems absurdly high.


> **EDIT:** Got `$#` working by removing it from `token_end()` and adding it to `variable_character()`. Does this break anything?

as long as comments still work, that is super!

I will review it and test it carefully.
